#!/bin/bash
#arvutamine ja ümardamine

echo -n "Sisestage ainepunktide arv:"
read x

echo -n "Sisestage nädalate arv:"
read y

vastus=`echo "scale=1;$x*26/$y" | bc`
vastussum="`echo "($vastus+0.9)/1" | bc`"

echo -n "Nädala eeldatav ajakulu: "
echo -n $vastussum
echo -n " tundi"
echo 
